export enum LeasingStatus {
  WAITING_FOR_APPROVE = 'WAITING_FOR_APPROVE',
  DENIED = 'DENIED',
  CANCELED = 'CANCELED',
  WAITING_FOR_DELIVERY = 'WAITING_FOR_DELIVERY',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  NEED_TO_RETURN = 'NEED_TO_RETURN',
  RETURNED = 'RETURNED'
}
